### PR TITLE
Add highlight voltage level

### PR DESCRIPTION
**Pull request by med-hedi**
Signed-off-by: Mohamed Hedi Khefacha <mohamed.hedi@rte-france.com>

### CODE REVIEW

**Review by geofjamg — CHANGES_REQUESTED** [review]
- the chosen selection color is not different enough and so on not visible.
image
  Could you use a color close to the sketch?
- In light this is even worst and there is also a glitch see the small white band on top of the selection:
image
- the substation selection is not done.
- do we try the triangle like in the sketch. it would probably help to improve the readability of the selection (in the current state I'am not totally convinced)? 
image

**Comment by geofjamg** [comment]
@mikatheo could you look at this?

**Comment by med-hedi** [comment]
@mikatheo before starting the US we agreed not to do the triangle, finally we do it?

**Comment by med-hedi** [comment]
@geofjamg ok, i will correct that

**Comment by mikatheo** [comment]
> @mikatheo before starting the US we agreed not to do the triangle, finally we do it?

We did indeed delay for the triangle last week, which may be the subject of another PR after discussion with the designers.
However, I agree with the other remarks, I just submitted them to Eline for more details. I will transfer the more precise elements to you very soon.

**Comment by geofjamg** [comment]
> > @mikatheo before starting the US we agreed not to do the triangle, finally we do it?
> 
> We did indeed delay for the triangle last week, which may be the subject of another PR after discussion with the designers.
> However, I agree with the other remarks, I just submitted them to Eline for more details. I will transfer the more precise elements to you very soon.

Ok

**Comment by med-hedi** [comment]
@geofjamg I made the necessary modifications and I validated the color codes with @ChristineHesse before pushing, for this PR we still have the triangle to do that will be the objective of another US.

**Review by geofjamg — APPROVED** [review]

**Pull request merged**
