### PR TITLE
Add substation to voltagelevel list

### PR DESCRIPTION
**Pull request by JacquesBorsenberger**

### CODE REVIEW

**Review by FranckLecuyer — COMMENTED** [review]
We can't just center a substation on a map anymore, without opening it at the same time
Is this what we want ?

**Review by geofjamg — CHANGES_REQUESTED** [review]
We lost the voltage level menu which was not the intend of this feature:
image

**Comment by JacquesBorsenberger** [comment]
> We can't just center a substation on a map anymore, without opening it at the same time
> Is this what we want ?

no, fixed it ;)

**Comment by JacquesBorsenberger** [comment]
> We lost the voltage level menu which was not the intend of this feature:

Requested by @mikatheo in US
> [Michael - 23/10] Suppression des trois points qui n'ont plus de sens pour le moment, et alourdisse l'IHM

**Comment by geofjamg** [comment]
> > We lost the voltage level menu which was not the intend of this feature:
> 
> Requested by @mikatheo in US
> 
> > [Michael - 23/10] Suppression des trois points qui n'ont plus de sens pour le moment, et alourdisse l'IHM

Ok

**Review by geofjamg — DISMISSED** [review]
The app has now a scroll bar. It was and is supposed to just fit the screen:
image
Could you fix it?

**Comment by mikatheo** [comment]
> The app has now a scroll bar. It was and is supposed to just fit the screen:
> image
> Could you fix it?

Fixed!

**Comment by mikatheo** [comment]
> The app has now a scroll bar. It was and is supposed to just fit the screen:
> image
> Could you fix it?

Fixed (adaptation of the auto-sizer height following the removal of the Model button)

**Review by jonenst — APPROVED** [review]

**Pull request merged**
