### PR TITLE
access to transformers modification dialog from SLD

### PR DESCRIPTION
**Pull request by souissimai**

### CODE REVIEW

**Review by AbdelHedhili — CHANGES_REQUESTED** [review]
`Warning: React does not recognize the `previousValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `previousvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.` in the console the first time you open the dialog

**Comment by AbdelHedhili** [comment]
Also to be discussed with the POs but it's weird having the cross to empty the ID field because you specifically want to edit the 2WT you clicked on + If you click on it, the id is coming back.

**Comment by AbdelHedhili** [comment]
> Also to be discussed with the POs but it's weird having the cross to empty the ID field because you specifically want to edit the 2WT you clicked on + If you click on it, the id is coming back.

answer: It's ok for now it'll be fixed later so there is only the warning issue

**Comment by souissimai** [comment]
> `Warning: React does not recognize the `previousValue`prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase`previousvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.` in the console the first time you open the dialog

it's an existing warning , I fixed it

**Review by Walid-Sahnoun — APPROVED** [review]
review ok
tests ok

**Review by AbdelHedhili — APPROVED** [review]

**Pull request merged**
