### PR TITLE
Add few props to lines in the spreadsheet

### PR DESCRIPTION
**Pull request by flomillot**
Add Series resistance, Series reactance, Shunt conductances and Shunt susceptances to lines in spreadsheet

note : filter seems not to be working with numbers with 1 fraction digit

### CODE REVIEW

**Comment by antoinebhs** [comment]
@flomillot, the others properties are defined: **Shunt conductance 1** / **Shunt Conductance 2** besides each others by default while here it's **Shunt conductance 1** /  [...] / **Shunt Conductance 2**. Have you checked with PO what's expected?

**Comment by flomillot** [comment]
> @flomillot, the others properties are defined: **Shunt conductance 1** / **Shunt Conductance 2** besides each others by default while here it's **Shunt conductance 1** / [...] / **Shunt Conductance 2**. Have you checked with PO what's expected?

I'm not sure to understand, I used the order defined in the US, is that the question ?

**Review by dbraquart — APPROVED** [review]
code: ok
tests: ok

**Review by antoinebhs — APPROVED** [review]
Code OK
Tests OK

**Pull request merged**
