### PR TITLE
Activate the validate button of phase tap changer when its table change

### PR DESCRIPTION
**Pull request by flomillot**
Signed-off-by: Florent MILLOT <millotflo@gmail.com>

### CODE REVIEW

**Comment by flomillot** [comment]
@Meklo @sBouzols does this fix seems correct for you ?

**Review by sBouzols — APPROVED** [review]
Code Review OK

**Comment by Meklo** [comment]
Works for me, I reckon you should also add the fix to `handleRatioTapRows`

**Comment by flomillot** [comment]
> 

Thanks, indeed you're right, I added it

**Pull request merged**
