### PR TITLE
Add delete voltage level on line illustration.

### PR DESCRIPTION
**Pull request by AAJELLAL**

### CODE REVIEW

**Review by SlimaneAmar — APPROVED** [review]

**Review by souissimai — CHANGES_REQUESTED** [review]
it seems that there is a difference between this illustrations and others. Maybe you can adjust size.  and fix background style 
Capture d’écran du 2024-01-01 14-30-43

 <path
       fill="#272727"
       id="delete-voltage-level-on-line-illu-background"
       d="M 1163.01,0 H 4.99249 C 2.23521,0 0,1.8681 0,4.17251 V 199.827 C 0,202.132 2.23521,204 4.99249,204 H 1163.01 c 2.75,0 4.99,-1.868 4.99,-4.173 V 4.17251 C 1168,1.8681 1165.76,0 1163.01,0 Z"
        />

**Comment by souissimai** [comment]
```
 <path
       fill="#272727"
       id="delete-voltage-level-on-line-illu-background"
       d="M 1163.01,0 H 4.99249 C 2.23521,0 0,1.8681 0,4.17251 V 199.827 C 0,202.132 2.23521,204 4.99249,204 H 1163.01 c 2.75,0 4.99,-1.868 4.99,-4.173 V 4.17251 C 1168,1.8681 1165.76,0 1163.01,0 Z"
        />``
```

**Review by souissimai — COMMENTED** [review]
Please change font-family:Roboto to sans-serif for line 1, line 2 and replacing line labels.

**Comment by AAJELLAL** [comment]
> Please change font-family:Roboto to sans-serif for line 1, line 2 and replacing line labels.

based on the gopro documentation we should use roboto.

**Review by souissimai — APPROVED** [review]

**Pull request merged**
