### PR TITLE
Add full screen single line diagram

### PR DESCRIPTION
**Pull request by med-hedi**
Signed-off-by: Mohamed Hedi Khefacha <mohamed.hedi@rte-france.com>

### CODE REVIEW

**Review by FranckLecuyer — CHANGES_REQUESTED** [review]
See comments sent in Slack ...

**Review by geofjamg — CHANGES_REQUESTED** [review]
Once maximized the visible part of the diagram is not the one of the window, see cut dagram:
image
- once maximized the app is not full screen anymore and a scroll bar is displayed:
image

**Comment by med-hedi** [comment]
@geofjamg for the scroll it would be fixed in the US didier to correct the problem with scroll

**Comment by geofjamg** [comment]
> @geofjamg for the scroll it would be fixed in the US didier to correct the problem with scroll

That would be a regression as there is no problem in the actual code. I do not any reason to fix it with a correct hard-coded offset as it is done today.
Anyway as you wish but this PR won't be merge with such a bug.

**Comment by med-hedi** [comment]
@geofjamg @FranckLecuyer all your comments have been fixed

**Review by geofjamg — CHANGES_REQUESTED** [review]
- Is it on purpose that you added a white border:
image
- scroll bar issue is not fixed
- panning limits are not correct when maximized

**Review by geofjamg — CHANGES_REQUESTED** [review]
There is a scroll issue when the diagram is maximized.

**Comment by med-hedi** [comment]
> There is a scroll issue when the diagram is maximized.

I fixed the scroll problem, it is only reproducible on firefox which is why I did not see it in the commit before because I tested on chrome

**Review by geofjamg — APPROVED** [review]

**Review by geofjamg — CHANGES_REQUESTED** [review]
There is a regression: we loose the pan position when running a loadflow.

**Comment by geofjamg** [comment]
> There is a regression: we loose the pan position when running a loadflow.

Ok this is not a regression because of this PR

**Review by geofjamg — APPROVED** [review]

**Pull request merged**
