### PR TITLE
update generator tabular modification and add connected to several ones

### PR DESCRIPTION
**Pull request by dbraquart**

### CODE REVIEW

**Comment by lilian-houdelet** [comment]
Traduction for voltageSetPoint is not present
image

**Review by lilian-houdelet — CHANGES_REQUESTED** [review]
Traduction for voltageSetPoint is not present
image

**Comment by dbraquart** [comment]
> Traduction for voltageSetPoint is not present image

It's an 'old' bug not related to this PR. There is no translation indeed, and it's not possible to change this attribute neither !

**Review by lilian-houdelet — APPROVED** [review]
Code OK
Test OK

**Review by ne0ds — APPROVED** [review]

**Pull request merged**
