### PR TITLE
fix gap when refresh sld

### PR DESCRIPTION
**Pull request by Walid-Sahnoun**
Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>

### CODE REVIEW

**Review by sBouzols — APPROVED** [review]
Code Review OK
Test OK
Console Warning check OK

**Review by sBouzols — CHANGES_REQUESTED** [review]
Must do the same for NAD

**Review by sBouzols — APPROVED** [review]
Then LinearProgress was doubled for NAD, you remove one as well good !
Test: divInvalid style with loadFlowStatus !== RunningStatus.SUCCEED still works OK

**Review by etiennehomer — APPROVED** [review]

**Comment by etiennehomer** [comment]
Tests OK

**Pull request merged**
