### PR TITLE
fix negative number for section in voltage<Level reztion form

### PR DESCRIPTION
**Pull request by ghazwarhili**

### CODE REVIEW

**Review by etiennehomer — CHANGES_REQUESTED** [review]
Row 97 of this file, change the condition : 
if (isNaN(watchSectionCount) || watchSectionCount <= 1) {

**Comment by ghazwarhili** [comment]
Okay, I can do it, but it doesn’t relate to the bug related t this PR. Otherwise, could you tell me the bug so I can adjust your proposal?

**Comment by etiennehomer** [comment]
> Okay, I can do it, but the changes request doesn’t related to this PR. Otherwise, could you tell me the bug so I can adjust your proposal?

It's kinda related to it. The "Switches between sections" field is visible when you type '-' in "Sections count". It should be hidden.

**Comment by ghazwarhili** [comment]
isNaN(watchSectionCount) : Argument type DeepPartialSkipArrayKey<FieldValues> is not assignable to parameter type number 

when I tried to set "-" in sectionsCount field 
Capture d’écran du 2024-10-30 16-10-20

what is the bug that you found to be fixed by this check isNaN(watchSectionCount)  ?

**Review by etiennehomer — APPROVED** [review]

**Pull request merged**
