### PR TITLE
[DO_NOT_MERGE] WIP Resize tree panel

### PR DESCRIPTION
**Pull request by EstherDarkish**

### CODE REVIEW

**Review by laurgarn — APPROVED** [review]
Works OK

**Review by YenguiSeddik — COMMENTED** [review]
code review: OK
Test: OK

**Review by YenguiSeddik — APPROVED** [review]

**Comment by EstherDarkish** [comment]
The product owners want to wait before merging this development.

**Comment by EstherDarkish** [comment]
This is too old, if one day we want this feature, we'll open a new PR. Closing this one.

**Pull request closed without merging**
