### PR TITLE
Disable the modification of a shunt compensator with multiple sections.

### PR DESCRIPTION
**Pull request by FranckLecuyer**
To be merged together with PR : https://github.com/gridsuite/network-modification-server/pull/280

### CODE REVIEW

**Review by Walid-Sahnoun — CHANGES_REQUESTED** [review]
when the node is not build
when we choose a shunt compensator with multi section
the error message is showed

**Comment by FranckLecuyer** [comment]
> when the node is not build when we choose a shunt compensator with multi section the error message is showed

**Review by Walid-Sahnoun — APPROVED** [review]
code ok
test ok

**Comment by FranckLecuyer** [comment]
> > when the node is not build when we choose a shunt compensator with multi section the error message is showed



> When trying to enter a non existant Id, we display an empty dialog: shunt

Right !
I fixed it

**Pull request merged**
